markdown: redcarpet
highlighter: pygments
permalink: /:title

url: http://colinhect.github.io
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
